### ISSUE TITLE
i3 try conky

### ISSUE THREAD

**Issue by wikimatze** [wikimatze/dotfiles#10]
- https://bbs.archlinux.de/viewtopic.php?id=20597
- Video: https://www.youtube.com/watch?v=fcO7zkK9AGM
- another setup manual: https://github.com/thefourtheye/ubuntu-setups/tree/master/i3/customize-i3-with-conky
- setup during Installation: https://sagar.se/using-conky-with-i3.html
- more setup: http://jesg.github.io/linux/2014/04/01/i3+conky.html
- another setup: https://gist.github.com/paulbdavis/4708828

More from @lam0r86:
http://skaletz.me/setup/i3/config                                                                                                                            │
http://skaletz.me/setup/i3/conky_i3bar                                                                                                                       │
http://skaletz.me/setup/i3/conkyrc                                                                                                                           │
ich merke ich muss mir mal github ansehen                                                                                                                    │
allein schon wegen dem UTF8 PRoblem und anderen fonts                                                                                                        │
http://skaletz.me/setup/i3/conky_i3bar-top                                                                                                                   │
http://skaletz.me/setup/i3/conkyrc-top                                                                                                                       │

**Comment by lam0r86** [comment]
https://i3wm.org/docs/user-contributed/conky-i3bar.html

**Comment by wikimatze** [comment]
Thanks for the link - so many new things to learn.

**Comment by lam0r86** [comment]
Can help if you want ;) got much more sites for conky and i3wm
https://skaletz.me/pics/archlinux/i3wm4.png my new config 

Cheers

**Comment by wikimatze** [comment]
Great, but first I need to cleanup my vimrc: https://github.com/wikimatze/vimfiles/commits?author=wikimatze&since=2016-08-31T22:00:00Z&until=2016-09-30T22:00:00Z
